openapi: 3.0.1
info:
  title: hospitalServiceAPi
  description: API Definition of hospitalServiceAPi
  version: 1.0.0
servers:
- url: http://localhost:8290/hospitalserviceapi
paths:
  /addPatient:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /patient/{patient_id}:
    delete:
      parameters:
      - name: patient_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
